{{- if .Values.global.daprEnabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: {{ .Values.kafka.broker }}
  - name: authRequired
    value: "false"
  - name: consumerGroup
    value: "tasks"
  - name: disableTls
    value: "true"
{{- end }}