apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  auth_secret: {{ .Values.config.authSecret | b64enc | quote }}
  database_url: {{ required "A valid database URL is required!" .Values.config.databaseUrl | default "sqlite:///./todo.db" | b64enc | quote }}
  openai_api_key: {{ required "A valid OpenAI API key is required!" .Values.config.openaiApiKey | default "" | b64enc | quote }}