apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: todo-app
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: follower
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: election
      protocol: TCP
      port: 3888
      targetPort: 3888
  type: ClusterIP