apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- patch-backend-minikube.yaml
- patch-frontend-minikube.yaml

configMapGenerator:
- name: minikube-config
  literals:
  - ENVIRONMENT=minikube
  - DEBUG=true