apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kafka-cluster.yaml
- dapr-components.yaml
- backend.yaml
- frontend.yaml
- notification-service.yaml
- recurring-task-service.yaml
- websocket-service.yaml